const actionTypes = {
  LOAD_PROMOTIONS: 'LOAD_PROMOTIONS',
  LOAD_PROMOTIONS_ERROR: 'LOAD_PROMOTIONS_ERROR',
  LOAD_PROMOTION: 'LOAD_PROMOTION',
  LOAD_PROMOTION_ERROR: 'LOAD_PROMOTION_ERROR',
  USER_STATE: ' USER_STATE',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  ADD_AND_LOAD_USER: 'ADD_AND_LOAD_USER',
  ADD_AND_LOAD_USER_ERROR: 'ADD_AND_LOAD_USER_ERROR'
}
export default actionTypes
