const actionTypes = {
  LOAD_PROMOTIONS: 'LOAD_PROMOTIONS',
  LOAD_PROMOTIONS_ERROR: 'LOAD_PROMOTIONS_ERROR',
  LOAD_PROMOTION: 'LOAD_PROMOTION',
  LOAD_PROMOTION_ERROR: 'LOAD_PROMOTION_ERROR'
}
export default actionTypes
